[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = [
    "MIT",
    "BSD-2-Clause",
    "CC0-1.0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
highlight = "all"
allow = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
deny = [
    # Each entry the name of a crate and a version range. If version is
    # not specified, all versions will be matched.
    #{ name = "ansi_term", version = "=0.11.0" },
]
skip = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
skip-tree = [
    #{ name = "ansi_term", version = "=0.11.0", depth = 20 },
]


[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-git = []
