permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
name: coverage
jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --timeout 120 --run-types Doctests --run-types Tests --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
